# These are supported funding model platforms

github: openpineaplehub
patreon: openpineaple
open_collective: 
ko_fi: supportpineaplehub
liberapay: openpineaple
issuehunt: openpine
buy_me_a_coffee: pineaplehub
